using UnityEngine;

//[RequireComponent(typeof(BoxCollider2D))]
public class DotBoxConR : MonoBehaviour
{
    [Header("µµĆ® ĽÓµµ")]
    public float moveSpeed = 400f;
    RectTransform dotboxImage;
    DeleteboxCon deleteboxCon;

    void Start()
    {
        dotboxImage = GetComponent<RectTransform>();
        deleteboxCon = FindAnyObjectByType<DeleteboxCon>();
    }

    void Update()
    {
        MoveToTarget();
    }

    void MoveToTarget()
    {
        if (dotboxImage == null || deleteboxCon.targetImage == null) return;

        Vector3 targetPos = deleteboxCon.targetImage.position; // world ±âÁŘ
        dotboxImage.position = Vector3.MoveTowards(
            dotboxImage.position,
            targetPos,
            moveSpeed * Time.deltaTime
        );
    }
}
