using UnityEngine;
using UnityEngine.UI;

public class NormalMusicBox : MonoBehaviour
{
    [Header("AudioSource")]
    [SerializeField] AudioSource musicSource;
    [Header("Musics")]
    [SerializeField] AudioClip music;
	[Header("Music Bar")]
	[SerializeField] Image musicBar;
	double nextStartTime = 5f;
    public bool MusicFin = false;
	private PlayerHP playerHPSc;
	private void Awake()
    {
	}
    void Start()
    {
		//      // УЙ Аю ПЙОр
		//      musicSource.clip = music[i];
		//musicSource.PlayScheduled(nextStartTime  + CheckRealTime.Instance.startTime);

		//      // ДйРН НУРл НУАЃ ПЙОр
		//      nextStartTime += musicSource.clip.length;
		playerHPSc = FindAnyObjectByType<PlayerHP>();
		double delay = 5.5;
        nextStartTime = AudioSettings.dspTime + delay; // ЧіРч DSP НУАЃПЁ СіПЌ НУАЃ УпАЁ
         musicSource.clip = music;
         musicSource.PlayScheduled(nextStartTime); // ПЙОрЕШ НУАЃПЁ УЙ Аю РчЛ§
	}
	private void Update()
	{
        if (!playerHPSc.isPlayerDead)
        {
			MusicBar();
			CheckMusicFinished();
		}
		else
		{
			musicSource.Stop();
		}
	}
	public void MusicBar()
	{
		musicBar.fillAmount = (float)CheckRealTime.inGamerealTime / (musicSource.clip.length+6f);
	}

    void CheckMusicFinished()
    {
        if(musicBar.fillAmount >= 1)
        {
            MusicFin = true;
		}
    }
}
