using Cysharp.Threading.Tasks;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.SceneManagement;

public class StageSelectGhostMove : MonoBehaviour
{
	public float moveSpeed = 4f;
	[SerializeField] Transform playerPos;
	public float chaseStartDistance = 10f;
	public float disableDistance = 1f;
    [SerializeField] BoxCollider clownCol;
    [SerializeField] BoxCollider skull;
    bool lastStageOn = false;
    void Awake()
    {
        if (playerPos == null)
            playerPos = GameObject.FindWithTag("Player")?.transform; //ЙАРНЧЅ КйРЬИщ nullРЬИщ nullЗЮ ЙнШЏ АГВмРг.
    }

    // Update is called once per frame
    private void Update()
    {
        // ХзНКЦЎПы РдЗТ
        if (Input.GetKeyDown(KeyCode.R))
            BossState.isBoss1Dead = true;
        if (Input.GetKeyDown(KeyCode.T))
            BossState.isBoss2Dead = true;

        // ЕЮ КИНКАЁ И№ЕЮ СзОњРЛ ЖЇ Чб ЙјИИ НЧЧр
        if (BossState.isBoss1Dead && BossState.isBoss2Dead && !lastStageOn)
        {
            MapSelected3.start3 = true;
            lastStageOn = true;

            var tm = FindObjectOfType<TextManager>();
            if (tm != null)
            {
                tm.StartStageDialogueAsync(4).Forget();
            }

            MoveScene().Forget();
        }
    }
    private async UniTask GhostMove(float durationSeconds)
    {
        float elapsed = 0f;

        while (elapsed < durationSeconds)
        {
            if (playerPos == null) break;

            float distance = Vector3.Distance(transform.position, playerPos.position);

            if (distance > disableDistance)
            {
                Vector3 dir = (playerPos.position - transform.position).normalized;
                transform.position += dir * moveSpeed * Time.deltaTime;
            }
            else if (distance <= disableDistance)
            {
                transform.SetParent(playerPos.transform, true);
                break;
            }

            elapsed += Time.deltaTime;
            await UniTask.Yield(PlayerLoopTiming.Update); //ДйРН Update ЗчЧС ХИРЬЙж ЖЇ ДйНУ НЧЧр
        }
    }


    private async UniTaskVoid MoveScene()
    {
        await UniTask.WaitUntil(() => !DialogueLineTrueORFalse.stage3_1True);
        clownCol.GetComponent<BoxCollider>().enabled = true;
        skull.GetComponent<BoxCollider>().enabled = true;
        await GhostMove(5f);
        MapSelected3.stop3 = true;

        var tm = FindObjectOfType<TextManager>();
        if (tm != null)
        {
            tm.StartStageDialogueAsync(5);
        }
        await UniTask.WaitUntil(() => !DialogueLineTrueORFalse.stage3_2True);
        SceneManager.LoadScene("LastStage");
    }
}
