using Cysharp.Threading.Tasks;
using Unity.VisualScripting;
using UnityEngine;
using UnityEngine.UIElements;

public class RotateOB : MonoBehaviour
{
    // Start is called once before the first execution of Update after the MonoBehaviour is created
    [Header("OBSpeed")]
    [SerializeField] float OBSpeed = 20f;
    private ParticleManager particleManager;
    private bool isInitialized = false;
    private Transform player;
    //bool isAttack = false;
    private void Awake()
    {
        player = GameObject.FindWithTag("Player").GetComponent<Transform>();
        particleManager = GameObject.FindWithTag("ParticleManager").GetComponent<ParticleManager>();
    }
    void Update()
    {
        transform.Rotate(0f, 0f, 100f * Time.deltaTime);
        if (gameObject.activeSelf == true)
        {
            OBMove();
        }

    }
    private async void OBMove()
    {
        await UniTask.Delay(5000);
        if (player == null)
            return;
        transform.LookAt(player.position);
        transform.Translate(Vector3.forward * OBSpeed * Time.fixedDeltaTime);
    }
    // Update is called once per frame
    private void OnEnable()
    {
        isInitialized = false;
        this.DelayInitialize().Forget();
    }

    private async UniTaskVoid DelayInitialize()
    {
        await UniTask.Yield(); // «— «¡∑π¿” ¥Î±‚
        isInitialized = true;
    }
    private void OnTriggerEnter(Collider col)
    {
        if (col.CompareTag("Player"))
        {
            GameObject.FindWithTag("Player").GetComponent<PlayerHP>().PlayerHPMinus().Forget();
            gameObject.SetActive(false);
        }
    }
    private void OnDisable()
    {
        if (!isInitialized) return; //Ω√¿€ ∆¯πﬂ πÊ¡ˆ¿”§ª§ª
        Vector3 effectPos = transform.position + new Vector3(0, 1f, 2f);
        if (effectPos == null)
            return;
        particleManager.PlayChairBoom(effectPos);
        if (particleManager == null)
            return;
        gameObject.SetActive(false);
    }
}
